// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/dreamvo/gilfoyle/ent/runtime.go

const (
	Version = "v0.5.3"                                          // Version of ent codegen.
	Sum     = "h1:YT3Sl28n7gGGOkQeYgeJsZmizJ1Iiy7psgkOtEk0aq4=" // Sum of ent codegen.
)
