// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/dreamvo/gilfoyle/ent/runtime.go

const (
	Version = "v0.5.1"                                          // Version of ent codegen.
	Sum     = "h1:XNIUdx1m8s2IBf36cnDoKKIaS2VaGJI/jkMKr8G9adE=" // Sum of ent codegen.
)
