// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/dreamvo/gilfoyle/ent/migrate"
	"github.com/google/uuid"

	"github.com/dreamvo/gilfoyle/ent/media"
	"github.com/dreamvo/gilfoyle/ent/mediaevents"
	"github.com/dreamvo/gilfoyle/ent/mediafile"
	"github.com/dreamvo/gilfoyle/ent/probe"

	"github.com/facebook/ent/dialect"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Media is the client for interacting with the Media builders.
	Media *MediaClient
	// MediaEvents is the client for interacting with the MediaEvents builders.
	MediaEvents *MediaEventsClient
	// MediaFile is the client for interacting with the MediaFile builders.
	MediaFile *MediaFileClient
	// Probe is the client for interacting with the Probe builders.
	Probe *ProbeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Media = NewMediaClient(c.config)
	c.MediaEvents = NewMediaEventsClient(c.config)
	c.MediaFile = NewMediaFileClient(c.config)
	c.Probe = NewProbeClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Media:       NewMediaClient(cfg),
		MediaEvents: NewMediaEventsClient(cfg),
		MediaFile:   NewMediaFileClient(cfg),
		Probe:       NewProbeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config:      cfg,
		Media:       NewMediaClient(cfg),
		MediaEvents: NewMediaEventsClient(cfg),
		MediaFile:   NewMediaFileClient(cfg),
		Probe:       NewProbeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Media.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Media.Use(hooks...)
	c.MediaEvents.Use(hooks...)
	c.MediaFile.Use(hooks...)
	c.Probe.Use(hooks...)
}

// MediaClient is a client for the Media schema.
type MediaClient struct {
	config
}

// NewMediaClient returns a client for the Media from the given config.
func NewMediaClient(c config) *MediaClient {
	return &MediaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `media.Hooks(f(g(h())))`.
func (c *MediaClient) Use(hooks ...Hook) {
	c.hooks.Media = append(c.hooks.Media, hooks...)
}

// Create returns a create builder for Media.
func (c *MediaClient) Create() *MediaCreate {
	mutation := newMediaMutation(c.config, OpCreate)
	return &MediaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Media entities.
func (c *MediaClient) CreateBulk(builders ...*MediaCreate) *MediaCreateBulk {
	return &MediaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Media.
func (c *MediaClient) Update() *MediaUpdate {
	mutation := newMediaMutation(c.config, OpUpdate)
	return &MediaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MediaClient) UpdateOne(m *Media) *MediaUpdateOne {
	mutation := newMediaMutation(c.config, OpUpdateOne, withMedia(m))
	return &MediaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MediaClient) UpdateOneID(id uuid.UUID) *MediaUpdateOne {
	mutation := newMediaMutation(c.config, OpUpdateOne, withMediaID(id))
	return &MediaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Media.
func (c *MediaClient) Delete() *MediaDelete {
	mutation := newMediaMutation(c.config, OpDelete)
	return &MediaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MediaClient) DeleteOne(m *Media) *MediaDeleteOne {
	return c.DeleteOneID(m.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MediaClient) DeleteOneID(id uuid.UUID) *MediaDeleteOne {
	builder := c.Delete().Where(media.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MediaDeleteOne{builder}
}

// Query returns a query builder for Media.
func (c *MediaClient) Query() *MediaQuery {
	return &MediaQuery{config: c.config}
}

// Get returns a Media entity by its id.
func (c *MediaClient) Get(ctx context.Context, id uuid.UUID) (*Media, error) {
	return c.Query().Where(media.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MediaClient) GetX(ctx context.Context, id uuid.UUID) *Media {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMediaFiles queries the media_files edge of a Media.
func (c *MediaClient) QueryMediaFiles(m *Media) *MediaFileQuery {
	query := &MediaFileQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(media.Table, media.FieldID, id),
			sqlgraph.To(mediafile.Table, mediafile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, media.MediaFilesTable, media.MediaFilesColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProbe queries the probe edge of a Media.
func (c *MediaClient) QueryProbe(m *Media) *ProbeQuery {
	query := &ProbeQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(media.Table, media.FieldID, id),
			sqlgraph.To(probe.Table, probe.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, media.ProbeTable, media.ProbeColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvents queries the events edge of a Media.
func (c *MediaClient) QueryEvents(m *Media) *MediaEventsQuery {
	query := &MediaEventsQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(media.Table, media.FieldID, id),
			sqlgraph.To(mediaevents.Table, mediaevents.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, media.EventsTable, media.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MediaClient) Hooks() []Hook {
	return c.hooks.Media
}

// MediaEventsClient is a client for the MediaEvents schema.
type MediaEventsClient struct {
	config
}

// NewMediaEventsClient returns a client for the MediaEvents from the given config.
func NewMediaEventsClient(c config) *MediaEventsClient {
	return &MediaEventsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mediaevents.Hooks(f(g(h())))`.
func (c *MediaEventsClient) Use(hooks ...Hook) {
	c.hooks.MediaEvents = append(c.hooks.MediaEvents, hooks...)
}

// Create returns a create builder for MediaEvents.
func (c *MediaEventsClient) Create() *MediaEventsCreate {
	mutation := newMediaEventsMutation(c.config, OpCreate)
	return &MediaEventsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MediaEvents entities.
func (c *MediaEventsClient) CreateBulk(builders ...*MediaEventsCreate) *MediaEventsCreateBulk {
	return &MediaEventsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MediaEvents.
func (c *MediaEventsClient) Update() *MediaEventsUpdate {
	mutation := newMediaEventsMutation(c.config, OpUpdate)
	return &MediaEventsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MediaEventsClient) UpdateOne(me *MediaEvents) *MediaEventsUpdateOne {
	mutation := newMediaEventsMutation(c.config, OpUpdateOne, withMediaEvents(me))
	return &MediaEventsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MediaEventsClient) UpdateOneID(id uuid.UUID) *MediaEventsUpdateOne {
	mutation := newMediaEventsMutation(c.config, OpUpdateOne, withMediaEventsID(id))
	return &MediaEventsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MediaEvents.
func (c *MediaEventsClient) Delete() *MediaEventsDelete {
	mutation := newMediaEventsMutation(c.config, OpDelete)
	return &MediaEventsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MediaEventsClient) DeleteOne(me *MediaEvents) *MediaEventsDeleteOne {
	return c.DeleteOneID(me.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MediaEventsClient) DeleteOneID(id uuid.UUID) *MediaEventsDeleteOne {
	builder := c.Delete().Where(mediaevents.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MediaEventsDeleteOne{builder}
}

// Query returns a query builder for MediaEvents.
func (c *MediaEventsClient) Query() *MediaEventsQuery {
	return &MediaEventsQuery{config: c.config}
}

// Get returns a MediaEvents entity by its id.
func (c *MediaEventsClient) Get(ctx context.Context, id uuid.UUID) (*MediaEvents, error) {
	return c.Query().Where(mediaevents.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MediaEventsClient) GetX(ctx context.Context, id uuid.UUID) *MediaEvents {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMedia queries the media edge of a MediaEvents.
func (c *MediaEventsClient) QueryMedia(me *MediaEvents) *MediaQuery {
	query := &MediaQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := me.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(mediaevents.Table, mediaevents.FieldID, id),
			sqlgraph.To(media.Table, media.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mediaevents.MediaTable, mediaevents.MediaColumn),
		)
		fromV = sqlgraph.Neighbors(me.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MediaEventsClient) Hooks() []Hook {
	return c.hooks.MediaEvents
}

// MediaFileClient is a client for the MediaFile schema.
type MediaFileClient struct {
	config
}

// NewMediaFileClient returns a client for the MediaFile from the given config.
func NewMediaFileClient(c config) *MediaFileClient {
	return &MediaFileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mediafile.Hooks(f(g(h())))`.
func (c *MediaFileClient) Use(hooks ...Hook) {
	c.hooks.MediaFile = append(c.hooks.MediaFile, hooks...)
}

// Create returns a create builder for MediaFile.
func (c *MediaFileClient) Create() *MediaFileCreate {
	mutation := newMediaFileMutation(c.config, OpCreate)
	return &MediaFileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MediaFile entities.
func (c *MediaFileClient) CreateBulk(builders ...*MediaFileCreate) *MediaFileCreateBulk {
	return &MediaFileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MediaFile.
func (c *MediaFileClient) Update() *MediaFileUpdate {
	mutation := newMediaFileMutation(c.config, OpUpdate)
	return &MediaFileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MediaFileClient) UpdateOne(mf *MediaFile) *MediaFileUpdateOne {
	mutation := newMediaFileMutation(c.config, OpUpdateOne, withMediaFile(mf))
	return &MediaFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MediaFileClient) UpdateOneID(id uuid.UUID) *MediaFileUpdateOne {
	mutation := newMediaFileMutation(c.config, OpUpdateOne, withMediaFileID(id))
	return &MediaFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MediaFile.
func (c *MediaFileClient) Delete() *MediaFileDelete {
	mutation := newMediaFileMutation(c.config, OpDelete)
	return &MediaFileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MediaFileClient) DeleteOne(mf *MediaFile) *MediaFileDeleteOne {
	return c.DeleteOneID(mf.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MediaFileClient) DeleteOneID(id uuid.UUID) *MediaFileDeleteOne {
	builder := c.Delete().Where(mediafile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MediaFileDeleteOne{builder}
}

// Query returns a query builder for MediaFile.
func (c *MediaFileClient) Query() *MediaFileQuery {
	return &MediaFileQuery{config: c.config}
}

// Get returns a MediaFile entity by its id.
func (c *MediaFileClient) Get(ctx context.Context, id uuid.UUID) (*MediaFile, error) {
	return c.Query().Where(mediafile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MediaFileClient) GetX(ctx context.Context, id uuid.UUID) *MediaFile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMedia queries the media edge of a MediaFile.
func (c *MediaFileClient) QueryMedia(mf *MediaFile) *MediaQuery {
	query := &MediaQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := mf.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(mediafile.Table, mediafile.FieldID, id),
			sqlgraph.To(media.Table, media.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mediafile.MediaTable, mediafile.MediaColumn),
		)
		fromV = sqlgraph.Neighbors(mf.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MediaFileClient) Hooks() []Hook {
	return c.hooks.MediaFile
}

// ProbeClient is a client for the Probe schema.
type ProbeClient struct {
	config
}

// NewProbeClient returns a client for the Probe from the given config.
func NewProbeClient(c config) *ProbeClient {
	return &ProbeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `probe.Hooks(f(g(h())))`.
func (c *ProbeClient) Use(hooks ...Hook) {
	c.hooks.Probe = append(c.hooks.Probe, hooks...)
}

// Create returns a create builder for Probe.
func (c *ProbeClient) Create() *ProbeCreate {
	mutation := newProbeMutation(c.config, OpCreate)
	return &ProbeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Probe entities.
func (c *ProbeClient) CreateBulk(builders ...*ProbeCreate) *ProbeCreateBulk {
	return &ProbeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Probe.
func (c *ProbeClient) Update() *ProbeUpdate {
	mutation := newProbeMutation(c.config, OpUpdate)
	return &ProbeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProbeClient) UpdateOne(pr *Probe) *ProbeUpdateOne {
	mutation := newProbeMutation(c.config, OpUpdateOne, withProbe(pr))
	return &ProbeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProbeClient) UpdateOneID(id uuid.UUID) *ProbeUpdateOne {
	mutation := newProbeMutation(c.config, OpUpdateOne, withProbeID(id))
	return &ProbeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Probe.
func (c *ProbeClient) Delete() *ProbeDelete {
	mutation := newProbeMutation(c.config, OpDelete)
	return &ProbeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ProbeClient) DeleteOne(pr *Probe) *ProbeDeleteOne {
	return c.DeleteOneID(pr.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ProbeClient) DeleteOneID(id uuid.UUID) *ProbeDeleteOne {
	builder := c.Delete().Where(probe.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProbeDeleteOne{builder}
}

// Query returns a query builder for Probe.
func (c *ProbeClient) Query() *ProbeQuery {
	return &ProbeQuery{config: c.config}
}

// Get returns a Probe entity by its id.
func (c *ProbeClient) Get(ctx context.Context, id uuid.UUID) (*Probe, error) {
	return c.Query().Where(probe.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProbeClient) GetX(ctx context.Context, id uuid.UUID) *Probe {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMedia queries the media edge of a Probe.
func (c *ProbeClient) QueryMedia(pr *Probe) *MediaQuery {
	query := &MediaQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := pr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(probe.Table, probe.FieldID, id),
			sqlgraph.To(media.Table, media.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, probe.MediaTable, probe.MediaColumn),
		)
		fromV = sqlgraph.Neighbors(pr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProbeClient) Hooks() []Hook {
	return c.hooks.Probe
}
