name: goreleaser

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [ published ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.15.x

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 12.20.x

      - name: Building dashboard assets
        run: |
          cd dashboard/ui
          yarn
          yarn build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.5.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
