// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)
