// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Video is the predicate function for video builders.
type Video func(*sql.Selector)
